### ISSUE TITLE
Update to support the latest Minecraft version

### ISSUE THREAD

**Issue by Jaffe2718** [Sloimayyy/mcschematic#2]
Now the official version of Minecraft has been updated to 1.19.4. Do you have any plans to update this Python library?

**Comment by Sloimayyy** [comment]
I'll have to update the documentation at one point, but most features should still work
For example, you can use 1.19.4+ blocks in mcschematic and save it as 1.19.3-, the schem will still work in 1.19.4+.
The only features that barely breaks are transform functions such as schem.getStructure().rotate( /* blah blah */) but you can still use them without worry if the blocks are 1.19.3-
