### ISSUE TITLE
Incorrectly parsing block states - mcschematic 11.4.2

### ISSUE THREAD

**Issue by adamwbull** [Sloimayyy/mcschematic#6]
The current mcschematic seems to have problems parsing stair and slab block states.

Take this simple example:
```py
import mcschematic

schem = mcschematic.MCSchematic()

schem.setBlock((0, 0, 0), "minecraft:oak_log[axis=z]")
schem.setBlock((0, 1, 0), "minecraft:oak_slab[type=top]")
schem.setBlock((0, 2, 0), "minecraft:oak_stairs[facing=west]")
schem.setBlock((0, 3, 0), "minecraft:oak_log[axis=y]")

schem.save(outputFolderPath='./schematics', schemName='schemtest', version=mcschematic.Version.JE_1_16)
```

Placing the created schem into this editor looks like so on https://beta.cubical.xyz/:

![image](https://github.com/Sloimayyy/mcschematic/assets/51730979/80233397-5b72-4b69-a736-91abb93e1e3d)

You can see why this arises by inspecting the block materials. The id contains the block state information for the stairs and slab, whereas it was properly parsed for the logs:

![image](https://github.com/Sloimayyy/mcschematic/assets/51730979/5177300d-1791-4a91-9940-ae1b3b422cba)

![image](https://github.com/Sloimayyy/mcschematic/assets/51730979/4df726c5-1f62-43d3-acf8-7aa1b1e830fd)

I would greatly appreciate some guidance on this, if there is a fix or trick already. I am also trying to navigate your mcschematic.py file myself and see if I can fix it, but it is a large and complex file. Any insight would be greatly appreciated.

My requirements.txt:
filelock==3.13.1
fsspec==2023.12.2
immutable-views==0.6.1
Jinja2==3.1.3
MarkupSafe==2.1.5
mcschematic==11.4.2
mpmath==1.3.0
nbtlib==2.0.4
networkx==3.2.1
numpy==1.26.3
sympy==1.12
torch==2.2.0
typing_extensions==4.9.0

**Comment by Sloimayyy** [comment]
Hi! Thanks for the report!
Have you tried pasting the schematic in your world? If it works then it's probably a Cubical.xyz bug rather than an MCSchematic one.

**Comment by adamwbull** [comment]
Hi, thank you for the reply.

I have tried using WorldEdit to paste it, and it does work. I believe the central WorldEdit plugin code has some sort of compensation for encounting an id with hard coded block states versus the block state being translated properly to the palette the first time, which these other technologies may not have, I'm working on comparing them all as well as mcschematic outputs.

But the generated schems do not work with:
- https://beta.cubical.xyz, as mentioned. I can place other .schem files onto that website from other sources besides mcschematic, and they will properly render stairs and slabs in cubical. 
- https://github.com/EngineHub/SchematicWebViewer/, which is what I was originally trying to get schematics to render on before testing on cubical.xyz because its a bit easier to visualize the issue.

So, a .schem file made with WorldEdit's //schem save, for example, works fine and represents stairs well with these two technologies and .schem files from mcschematic are not working with them.

**Comment by adamwbull** [comment]
Hi again, I figured out what the issue was, and you are right it seems to be due to those two technologies.

I have been able to get it to render fine on cubical by specifying every block state possibility:
```py
schem.setBlock((0, 0, 0), "minecraft:oak_log[axis=z]")
schem.setBlock((0, 1, 0), "minecraft:oak_slab[type=top,waterlogged=false]")
schem.setBlock((0, 2, 0), "minecraft:oak_stairs[facing=west,half=bottom,shape=straight,waterlogged=false]")
schem.setBlock((0, 3, 0), "minecraft:oak_log[axis=y]")
```

I am still having issues with https://github.com/EngineHub/SchematicWebViewer/ not being able to render schems created by mcschematic yet it can render WorldEdit schematics fine, so I will keep trying to figure out what the difference is.

**Comment by adamwbull** [comment]
I figured out the issues with SchematicWebViewer as well, and it was unrelated to mcschematic. Thank you for your assistance and work on this amazing module!
